apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      containers:
      - name: metrics-api
        image: ethanfox/keda-metrics-api:latest
        ports:
        - containerPort: 7051
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-api-service
spec:
  selector:
    app: metrics-api
  ports:
    - protocol: TCP
      port: 7051
      targetPort: 7051
  type: LoadBalancer